"""feat: add field for verified medicine

Revision ID: 0440f768a49e
Revises: a582e8996f05
Create Date: 2025-12-06 22:16:14.048603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0440f768a49e'
down_revision: Union[str, Sequence[str], None] = 'a582e8996f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "medicines",
        sa.Column(
            "is_verified",
            sa.Boolean(),
            nullable=False,
            server_default="false"
        )
    )
    op.alter_column("medicines", "is_verified", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicines', 'is_verified')
    # ### end Alembic commands ###
