"""refactor: is_verified in medical to flags for any situation

Revision ID: 38eaf25aac72
Revises: e1f08879a722
Create Date: 2025-12-07 15:26:44.842489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38eaf25aac72'
down_revision: Union[str, Sequence[str], None] = 'e1f08879a722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicines', sa.Column('flags', sa.Integer(),
            server_default='1'))
    op.drop_column('medicines', 'is_verified')
    op.alter_column("medicines", "flags", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicines', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('medicines', 'flags')
    # ### end Alembic commands ###
