"""feat: add medecine models

Revision ID: 553f8afd8469
Revises: de1851e6f2e5
Create Date: 2025-12-06 19:08:06.161877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '553f8afd8469'
down_revision: Union[str, Sequence[str], None] = 'de1851e6f2e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine_kits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('medicine_type', sa.Enum('TABLETS', 'CAPSULES', 'OINTMENT', 'CREAM', 'DROPS', 'SYRUP', 'SPRAY', 'SOLUTION', 'POWDER', 'SUPPOSITORIES', 'PATCH', 'OTHER', name='medicinetype', native_enum=False), nullable=False),
    sa.Column('category', sa.Enum('PAINKILLER', 'ANTI_INFLAMMATORY', 'ANTIBIOTIC', 'ANTIVIRAL', 'ANTIHISTAMINE', 'ANTISEPTIC', 'VITAMIN', 'CARDIOVASCULAR', 'DIGESTIVE', 'RESPIRATORY', 'DERMATOLOGICAL', 'NEUROLOGICAL', 'OTHER', name='medicinecategory', native_enum=False), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('active_ingredient', sa.String(length=200), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_name'), 'medicines', ['name'], unique=False)
    op.create_table('medicine_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medicine_kit_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medicine_kit_id'], ['medicine_kits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_medicine_kits',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('medicine_kit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_kit_id'], ['medicine_kits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'medicine_kit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_medicine_kits')
    op.drop_table('medicine_items')
    op.drop_index(op.f('ix_medicines_name'), table_name='medicines')
    op.drop_table('medicines')
    op.drop_table('medicine_kits')
    # ### end Alembic commands ###
