"""refactor: models medicine

Revision ID: a582e8996f05
Revises: 553f8afd8469
Create Date: 2025-12-06 20:59:43.421223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a582e8996f05'
down_revision: Union[str, Sequence[str], None] = '553f8afd8469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicine_items', 'photo_path')
    op.drop_column('medicine_items', 'purchase_date')
    op.add_column('medicines', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_column('medicines', 'manufacturer')
    op.drop_column('medicines', 'active_ingredient')
    op.drop_column('medicines', 'instructions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicines', sa.Column('instructions', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('medicines', sa.Column('active_ingredient', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('medicines', sa.Column('manufacturer', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('medicines', 'notes')
    op.add_column('medicine_items', sa.Column('purchase_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('medicine_items', sa.Column('photo_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
