"""feat: add field deleted in medkit

Revision ID: e1f08879a722
Revises: 0440f768a49e
Create Date: 2025-12-07 13:14:14.561329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f08879a722'
down_revision: Union[str, Sequence[str], None] = '0440f768a49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine_kits', sa.Column('deleted', sa.Boolean(), nullable=False,
            server_default="false"))
    op.alter_column("medicine_kits", "deleted", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicine_kits', 'deleted')
    # ### end Alembic commands ###
